apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-poc
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-poc
  template:
    metadata:
      labels:
        app: nginx-poc
    spec:
      containers:
      - name: nginx-poc
        image: asia-south1-docker.pkg.dev/kiran-499609/poc-repo/nginx-poc:190739bf286a48cedce3767c0a0b4a693208b8fa
        ports:
        - containerPort: 80
