apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-poc
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-poc
  template:
    metadata:
      labels:
        app: nginx-poc
    spec:
      containers:
      - name: nginx-poc
        image: asia-south1-docker.pkg.dev/kiran-499609/poc-repo/nginx-poc:6a09dc152370c4e717c9fa4af3d7c365f4fa4782
        ports:
        - containerPort: 80
