apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-external-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: "nginx-external-ip"
    networking.gke.io/managed-certificates: ""
spec:
  tls:
  - hosts:
    - kirann.xyz
    - "*.kirann.xyz"
    secretName: wildcard-kirann-xyz-tls
  rules:
  - host: app.kirann.xyz
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-poc-service
            port:
              number: 80
  - host: api.kirann.xyz
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-poc-sse-service
            port:
              number: 8080
